[package]
name = "pso-rs"
version = "2.2.4"
authors = ["Christos Zonios <czonios@gmail.com>"]
description = "An easy-to-use, simple Particle Swarm Optimization implementation in Rust."
edition = "2021"
license = "MIT"
repository = "https://github.com/czonios/pso-rs"
homepage = "https://czonios.github.io/pso-rs/"
documentation = "https://docs.rs/pso-rs/latest/pso_rs/"
exclude = [
    "src/bin",
    "screenshots"
]

[features]
default = []
progress = ["dep:indicatif"]

[dependencies]
rand = "^0.8.4"
rand_chacha = "^0.3"
indicatif = { version = "^0.18.4", optional = true }
rayon = "^1.5.1"
log = "0.4"

[dev-dependencies]
env_logger = "0.11"
test-log = "0.2"
